name: cd-dev

on:
  workflow_run:
    workflows: [ "ci-dev" ]
    types:
      - completed
jobs:
  on-success:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: ${{ secrets.DEPLOY_SCRIPT }}