name: ci-prod

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure resource directory exists
        run: mkdir -p ./src/main/resources

      - name: injection-application.yml
        run: echo -E "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Execute Gradle build and tests
        run: ./gradlew clean build

      - name: Generate JaCoCo Test Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Check test coverage
        run: |
          COVERAGE=$(grep -oP '(?<=<line-rate>)[0-9.]+(?=</line-rate>)' build/reports/jacoco/test/jacocoTestReport.xml | head -1)
          if (( $(echo "$COVERAGE < 0.80" | bc -l) )); then
            echo "Test coverage $COVERAGE is below the threshold of 80%."
            exit 1
          fi
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Execute Gradle build and analyze
        run: ./gradlew jib