name: cicd-prod

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure resource directory exists
        run: mkdir -p ./src/main/resources

      - name: injection-application.yml
        run: echo -E "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Execute Gradle build and tests
        run: ./gradlew clean build

      - name: Generate JaCoCo Test Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          title: "Code Coverage"
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          update-comment: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Execute Gradle build and analyze
        run: ./gradlew jib

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: ${{ secrets.DEPLOY_SCRIPT }}